import pandas as pd
import numpy as np

print("Reading dataset using Pandas package")
print("=======================e=============")
print("\n")
file_csv = "E:\MSc Data Science\Data Science Techniques and Applications\Coursework\\tweets.csv"
df = pd.read_csv(file_csv)
print("\n")

print("Attributes of tweet")
print("===================")
print("\n")
print(df.info())
print("\n")

print("Fanboys and number of tweets")
print("============================")
print("\n")
fanboys = df["name"].unique()
print("Type of data structure:", type(fanboys))
print("Number of fanboys:", len(fanboys))
print(fanboys)
print("\n")

print("Usernames")
print("==============================")
print("\n")
username = df["username"].unique()
print("Type of data structure:", type(username))
print("Number of usernames:", len(username))
print("\n")

print("Number of followers per fanboy")
print("==============================")
print("\n")
followers = df["followers"].unique()
print("Type of data structure:", type(followers))
print("Range:", min(followers), max(followers))
print("Number of followers:", len(followers))
print(followers)
print("\n") 

print("Number of tweets per fanboy")
print("===========================")
print("\n")
status = df["numberstatuses"].unique()
print("Type of data structure:", type(status))
print("Range:", min(status), max(status))
print("Number of statuses:", len(status))
print(status)
print("\n")

print("Number of locations")
print("===================")
print("\n")
location = df["location"].unique()
print("Type of data structure:", type(location))
print("Number of locations:", len(location))
print(location)
print("\n")
